trigger:
  branches:
    include:
      - main

stages:
  - stage: NPM12
    condition: |
      and(
        ne(variables['Build.Reason'], 'PullRequest'),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - job: NPM
        displayName: 'NPM Install'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: 'my-app'

  - stage: Deploy
    condition: |
      eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: Deploy
        displayName: 'Deploy to Production'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "Deploying..."
          # SonarQube tasks
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'sonarconnection-gs'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'GS-test'
              cliProjectName: 'GS-test'
              cliSources: '.'
              extraProperties: |
                sonar.javascript.lcov.reportPaths=./coverage/lcov.info

          - task: SonarQubeAnalyze@5
            inputs:
              jdkVersion: 'JAVA_HOME_11_X64'

          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'